# Generated by Django 2.1.1 on 2018-09-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
