# Generated by Django 2.1.1 on 2018-11-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
