# Generated by Django 2.1.1 on 2018-11-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20181108_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1', to='games.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2', to='games.Player'),
            preserve_default=False,
        ),
    ]
